# -*- coding: utf-8 -*-
"""26.05.2023. 4 potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDOquGBF0UEZY0AgKOdY9MSFzhzNO3Jw
"""

print ('Привет мир')